---

container_runtime: "{{ cluster_container_runtime  | default('crio') }}"

cr_containerd_kernel_modules:
  - overlay
  - br_netfilter

cr_containerd_packages_names:
  - "containerd.io=1.4.12-1"
  - "cri-tools=1.19.0-00"

cr_containerd_hold_package_name:
  - "containerd.io"

cr_containerd_root_dir_path: '/app/containerd'


cr_containerd_socket_dir: "/run/containerd"

cr_no_log: "{{ cluster_no_log | default('true') }}"


cr_crio_kernel_modules:
  - overlay
  - br_netfilter

cr_crio_packages_names:
  - "cri-o=1.36.4-1.1"
  - "cri-tools=1.36.0-1.1"

cr_crio_dnf_packages_names:
  - "cri-o1.36"
  - "cri-tools1.36"
  

# cr_crio_hold_package_name:
#   - "cri-o"

cr_crio_root_dir_path: '/app/crio'
cr_crio_force_restart: false

cr_crio_auth_hostname: "{{ nexus_hostname | default('') }}"
cr_crio_insecure_registries: []

cr_crio_sysctl_parameters:
  - "net.bridge.bridge-nf-call-ip6tables=1"
  - "net.bridge.bridge-nf-call-iptables=1"
  - "net.ipv4.ip_forward=1"

cr_crio_registry_mapping_mirrors: []
cr_crio_registry_mapping_prefix_default: "{{ cluster_registry | default('unnamed-registry') }}"
cr_crio_registry_mapping_mirror_default: ""
