---
- name: import apt install
  vars:
    apt_install:
      - "kubelet={{ kubelet_version }}"
  ansible.builtin.import_role:
    name: common/apt_install
  notify:
    - restart kubelet
  when: ansible_distribution.split(' ') | first | lower in ['ubuntu', 'astra', 'debian']

- name: "Import dnf install"
  vars:
    dnf_install:
      - "kubelet-{{ kubelet_version }}*"
  ansible.builtin.import_role:
    name: common/dnf_install
  when: ansible_distribution.split(' ') | first | lower in ['red', 'almalinux', 'centos', 'oraclelinux']

- name: Remove swapfile from /etc/fstab
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none

- name: systemd swap disable  # noqa ignore-errors
  systemd:
    name: swap.target
    masked: true
    state: stopped
    enabled: false
  ignore_errors: true

- name: check swap
  ansible.builtin.command:
    cmd: /sbin/swapoff -a
  changed_when: false

- name: ensure kubelet is enabled
  ansible.builtin.systemd:
    name: kubelet.service
    enabled: true

- name: kubelet force restart
  command: /bin/true
  when:
    - kubelet_force_restart
  notify:
    - restart kubelet
