apiVersion: audit.k8s.io/v1beta1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
# Исключения для конфигмапов лидер элекшена истио, ингресс и сертменеджер
rules:
  - level: None
    resources:
    - group: ""
      resources:
        - configmaps
      resourceNames:
        - istio-leader
        - ingress-controller-leader
        - istio-gateway-status-leader
        - istio-namespace-controller-election
        - istio-gateway-deployment-leader
        - cert-manager-cainjector-leader-election
        - cert-manager-controller
# log auth from dex
  - level: Request
    resources:
      - group: "dex.coreos.com"
        resources:
          - authrequests
          - refreshtokens
    verbs:
      - update
      - patch

# log rbac changes
  - level: Request
    resources:
      - group: "rbac.authorization.k8s.io"
        resources:
          - roles
          - clusterroles
          - rolebindings
          - clusterrolebindings
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
# log anu verb with secrets
  - level: Metadata
    resources:
      - resources:
          - secrets
          - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
# log pods and resources
  - level: Request
    verbs:
      - create
      - update
      - patch
      - delete
      - deletecollection
    resources:
      - group: ""
        resources:
          - pods
          - replicacontrollers
          - container
          - serviceaccounts
          - resourcequotas
          - persistentvolumes
          - persistentvolumeclaims
          - limitranges
      - group: "apps"
        resources:
          - daemonsets
          - deployments
          - deployments/rollback
          - deployments/scale
          - replicasets
          - statefulsets
      - group: "batch"
        resources:
          - jobs
          - cronjobs
# Log any actions services
  - level: Request
    verbs:
      - create
      - patch
      - replace
      - delete
      - deletecollection
    resources:
      - group: ""
        resources:
          - services
# Log webhook actions, crd, pdb
  - level: Request
    verbs:
      - create
      - patch
      - replace
      - delete
      - deletecollection
    resources:
      - group: "apiextensions.k8s.io"
        resources:
          - customresourcedefinitions
      - group: "admissionregistration.k8s.io"
        resources:
          - validatingwebhookconfigurations
          - mutatingwebhookconfigurations
      - group: "policy"
        resources:
          - poddisruptionbudgets
# Log ingresses
  - level: Request
    verbs:
      - create
      - patch
      - replace
      - delete
      - deletecollection
    resources:
      - group: "networking.k8s.io"
        resources:
          - ingresses
          - networkpolicies

# log any actions of admins
  - level: Request
    userGroups:
      - system:cluster-admins
      - admins
      - kubernetes-admin
  # disable another logs
  # Ignore helthchecks and version requests
  - level: None
    nonResourceURLs:
      - "/metrics"
      - "/version"
      - "/healthz"
      - "/readyz"
      - "/livez"
      - "/metrics"
  - level: None
    userGroups:
      - system:nodes
  - level: None
    users:
      - system:apiserver
      - system:kube-controller-manager
      - system:kube-scheduler
