---
#- name: overwrite image list
#  ansible.builtin.set_fact:
#    pull_images_list: "{{ pull_images_list | map('regex_replace','^(.*?)\/(.*$)', pull_image_registry + '/\\2' ) | list }}"

# tasks file for pull_images
- name: check pulled image
  ansible.builtin.command:
    cmd: "crictl images -o yaml"
  register: pull_image_crictl_imagelist
  changed_when: false

#  ansible parser can't manipulate with objects that came from string
- name: set_fact
  ansible.builtin.set_fact:
    pull_images_pulled_image: "{{ pull_image_crictl_imagelist.stdout | from_yaml  }}"

- name: pull missing images
  ansible.builtin.command:
    cmd: "crictl pull {{ item }}"
  changed_when: item not in (pull_images_pulled_image['images'] | map(attribute='repoTags') | flatten )
  loop: "{{ pull_images_list }}"
  when:
    - item not in (pull_images_pulled_image['images'] | map(attribute='repoTags') | flatten )
  register: pull_image_retry
  retries: 10
  delay: 10
  until: pull_image_retry.rc == 0
