---
galaxy_info:
  author: EG
  description: Role configure sysctl
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - noble
  galaxy_tags: []

dependencies: []
