---

- hosts: load_balancers
  gather_facts: true
  become: true
  roles:
    - role: lb/haproxy
      when: cluster_lb_enabled | default(false) | bool
      tags:
        - lb
        - haproxy
    - role: lb/keepalived
      when:
        - cluster_lb_enabled | default(false) | bool
        - cluster_lb_vip_enabled | default(false) | bool
      tags:
        - lb
        - keepalived
