---
haproxy_enabled: true
haproxy_bind_address: "0.0.0.0"
haproxy_bind_port: 6443
haproxy_backend_group: "masters"
haproxy_backend_port: 6443
haproxy_backend_servers: []
haproxy_default_frontend_name: "kube-apiserver"
haproxy_default_backend_name: "kube-apiserver"
haproxy_maxconn: 2000
haproxy_timeout_connect: "5s"
haproxy_timeout_client: "1m"
haproxy_timeout_server: "1m"
haproxy_retries: 3
haproxy_check_interval: "3s"
haproxy_check_fall: 3
haproxy_check_rise: 2
