---

- name: Print OS family
  debug:
    msg: "Distribution is {{ ansible_distribution }}"

- name: Configure Repositories for Debian/Ubuntu
  include_tasks: set_packages_debian.yml
  when: ansible_distribution.split(' ') | first | lower in ['ubuntu', 'astra', 'debian']

- name: Configure Repositories for RedOS/CentOS/AlmaLinux
  include_tasks: set_packages_rhel.yml
  when: ansible_distribution.split(' ') | first | lower in ['red', 'almalinux', 'centos', 'oraclelinux']
