---

set_journald: true
set_journald_ansible_managed: '# This file managed by containerization group playbook'
set_journald_storage_option: "auto"
set_journald_compress_option: "yes"
set_journald_seal_option: "yes"
set_journald_splitmode: "uid"
set_journald_sync_interval: "5m"
set_journald_rate_limit_interval: "30s"
set_journald_rate_limit_burst: "1000"
set_journald_system_max_use: "4G"
set_journald_system_keep_free: "1G"
set_journald_max_file_size: "10M"
set_journald_runtime_max_use: ""
set_journald_runtime_keep_free: ""
set_journald_runtime_max_file_size: ""
set_journald_max_retention_sec: ""
set_journald_max_file_sec: "1month"
set_journald_forward_to_syslog: "yes"
set_journald_forward_to_kmsg: "no"
set_journald_forward_to_console: "no"
set_journald_forward_to_wall: "yes"
set_journald_tty_path: "/dev/console"
set_journald_max_level_store: "debug"
set_journald_max_level_syslog: "debug"
set_journald_max_level_kmsg: "notice"
set_journald_max_level_console: "info"
set_journald_max_level_wall: "emerg"
