---
- name: create kubeadm directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0700
    state: directory
  loop:
    - /etc/kubernetes/kubeadm
    - /etc/kubernetes/kubeadm/patches
    - /etc/kubernetes/tmp
    - "{{ kubeadm_masters_init_etc_data_dir }}"
    - "{{ kubeadm_masters_init_audit_log_directory }}"
    - "{{ kubeadm_masters_init_kubeadm_tmp_dir }}"

- name: Initialize API server cert SANs
  ansible.builtin.set_fact:
    kubeadm_masters_init_apiserver_cert_sans_effective: >-
      {{
        (
          (kubeadm_masters_init_apiserver_cert_sans | default([]))
          + [kubeadm_masters_init_cluster_api_hostname]
          + ([cluster_public_api_fqdn] if (cluster_public_api_fqdn is defined and (cluster_public_api_fqdn | string | length > 0)) else [])
          + [ansible_default_ipv4.address, inventory_hostname]
        )
        | reject('equalto', '')
        | unique
        | list
      }}

- name: Add load balancer endpoints to API server cert SANs
  ansible.builtin.set_fact:
    kubeadm_masters_init_apiserver_cert_sans_effective: >-
      {{
        (
          kubeadm_masters_init_apiserver_cert_sans_effective
          + [hostvars[item].get('ansible_host') | default(hostvars[item].get('ansible_default_ipv4', {}).get('address'), true) | default(item, true)]
        )
        | reject('equalto', '')
        | unique
        | list
      }}
  loop: "{{ groups.get('load_balancers', []) }}"

- name: template kubeadm init config
  ansible.builtin.template:
    src: "init-kubeadm.yaml.j2"
    dest: "/etc/kubernetes/kubeadm/init-kubeadm.yaml"
    owner: root
    group: root
    mode: 0600
  notify:
    - kubeadm upgrade

- name: copy audit policy
  ansible.builtin.copy:
    src: policy.yaml
    dest: "{{ kubeadm_masters_init_audit_config }}"
    owner: root
    group: root
    mode: 0600
  when:
    - kubeadm_masters_init_audit_enabled | bool
  notify:
    - kubeadm upgrade

- name: Get firewall status
  ansible.builtin.service_facts:
  no_log: true
  register: service_firewall_facts
  when: ansible_distribution.split(' ') | first | lower in ['red', 'almalinux', 'centos', 'oraclelinux']

- name: Stop and disable firewalld
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - service_firewall_facts.ansible_facts.services['firewalld.service'] is defined
    - service_firewall_facts.ansible_facts.services['firewalld.service']['status'] != 'not-found'

- name: Configure SELinux
  when:
    - ansible_selinux is defined
    - ansible_selinux.status != 'disabled'
  block:

    - name: Install selinux packages(RHEL)
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - "python3-policycoreutils"
        - "python3-libselinux"
        - "container-selinux"

    - name: Add ports for Kubernetes and Cilium
      community.general.seport:
        ports: "{{ item.ports }}"
        proto: "{{ item.proto }}"
        setype: "container_port_t"
        state: present
      loop:
        - { ports: "6443", proto: "tcp" }
        - { ports: "10250", proto: "tcp" }
        - { ports: "2379-2380", proto: "tcp" }
        - { ports: "8472", proto: "udp" }
        - { ports: "51871", proto: "udp" }
        - { ports: "443", proto: "tcp" }
        - { ports: "80", proto: "tcp" }

    - name: Enable all container SELinux booleans
      ansible.builtin.seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - container_connect_any
        - container_manage_cgroup
        - container_use_devices
        - container_read_certs
        - container_use_dri_devices

    - name: Set SELinux to permissive mode
      ansible.builtin.selinux:
        policy: targeted
        state: permissive
      register: selinux_permissive
      ignore_errors: yes

    - name: Reboot if SELinux mode changed
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: selinux_permissive is changed
      ignore_errors: yes

    - name: Verify SELinux status
      ansible.builtin.command: getenforce
      register: selinux_status
      changed_when: false

- name: init first master
  run_once: true
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --config
      - /etc/kubernetes/kubeadm/init-kubeadm.yaml
      - --v=5
    creates: /etc/kubernetes/admin.conf
  no_log: "{{ kubeadm_masters_init_no_log }}"
  register: kubeadm_init

- name: fetch bootstrap token
  run_once: true
  ansible.builtin.command:
    cmd: >-
      kubeadm token create --config /etc/kubernetes/kubeadm/init-kubeadm.yaml --v=5
  register: kubeadm_masters_init_join_command
  changed_when: false
  no_log: "{{ kubeadm_masters_init_no_log }}"

- name: upload certificate to kubead-serts store
  no_log: "{{ kubeadm_masters_init_no_log }}"
  ansible.builtin.command:
    cmd: >-
      kubeadm init phase upload-certs --upload-certs --config /etc/kubernetes/kubeadm/init-kubeadm.yaml --v=5
  changed_when: false
  register: kubeadm_masters_init_certificates_key
  run_once: true

- name: get sha256 hash CA certificate
  run_once: true
  changed_when: false
  ansible.builtin.raw: >-
    openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: kubeadm_masters_init_ca_hash

- name: template join kubeadm config
  ansible.builtin.template:
    src: join-kubeadm.yaml.j2
    dest: /etc/kubernetes/kubeadm/join-kubeadm.yaml
    owner: root
    group: root
    mode: 0600
  no_log: "{{ kubeadm_masters_init_no_log }}"

- name: join other masters to cluster
  ansible.builtin.command:
    argv:
      - kubeadm
      - join
      - --config
      - /etc/kubernetes/kubeadm/join-kubeadm.yaml
    creates: /etc/kubernetes/admin.conf
  no_log: "{{ kubeadm_masters_init_no_log }}"
  register: kubeadm_join
  retries: 3
  delay: 30

- name: create cloud-manager user
  run_once: true
  no_log: "{{ kubeadm_masters_init_no_log }}"
  ansible.builtin.command:
    cmd: >-
      kubeadm kubeconfig user --client-name cloud-manager --config /etc/kubernetes/kubeadm/init-kubeadm.yaml --validity-period 1h --org 'system:masters'
  register: kubeadm_temp_config
  changed_when: false

- name: create kubeconfig directory
  connection: local
  become: "{{ kubeadm_masters_init_become }}"
  run_once: true
  ansible.builtin.file:
    path: "{{ kubeadm_masters_init_kubeconfig | dirname }}"
    state: directory
    mode: "0755"

- name: copy token to controller
  become: "{{ kubeadm_masters_init_become }}"
  connection: local
  run_once: true
  no_log: "{{ kubeadm_masters_init_no_log }}"
  copy:
    content: "{{ kubeadm_temp_config.stdout }}"
    dest: "{{ kubeadm_masters_init_kubeconfig }}"
    mode: "0755"
