---

- name: Gather distribution facts
  setup:
    filter:
      - ansible_distribution

- name: Display distribution
  debug:
    var: ansible_distribution

- name: "Setup {{ container_runtime }}"
  import_tasks: "setup_containerd.yml"
  when:
    - container_runtime == "containerd"

- name: "Setup {{ container_runtime }}"
  import_tasks: "setup_crio.yml"
  when:
    - container_runtime == "crio"
