---
galaxy_info:
  author: EG
  description: Add and update helm repositories
  license: MIT

  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags: []

allow_duplicates: true
