---

galaxy_info:
  author: EG
  description: Role of generating certificates in k8s cluster
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags: []
dependencies: []
